people = [
    {
        "name": "Beyoncé",
        "profession": "a Musician",
        "country": "United States",
        "followers": 310000000,
    },
    {
        "name": "Cristiano Ronaldo",
        "profession": "a Footballer",
        "country": "Portugal",
        "followers": 630000000,
    },
    {
        "name": "Dwayne Johnson",
        "profession": "an Actor",
        "country": "United States",
        "followers": 390000000,
    },
    {
        "name": "Lionel Messi",
        "profession": "a Footballer",
        "country": "Argentina",
        "followers": 500000000,
    },
    {
        "name": "Taylor Swift",
        "profession": "a Musician",
        "country": "United States",
        "followers": 280000000,
    },
    {
        "name": "Roger Federer",
        "profession": "a Tennis Player",
        "country": "Switzerland",
        "followers": 12000000,
    },
    {
        "name": "Adele",
        "profession": "a Musician",
        "country": "United Kingdom",
        "followers": 55000000,
    },
    {
        "name": "Usain Bolt",
        "profession": "a Sprinter",
        "country": "Jamaica",
        "followers": 13000000,
    },
    {
        "name": "Shakira",
        "profession": "a Musician",
        "country": "Colombia",
        "followers": 89000000,
    },
    {
        "name": "Serena Williams",
        "profession": "a Tennis Player",
        "country": "United States",
        "followers": 17000000,
    },
    {
        "name": "Ed Sheeran",
        "profession": "a Musician",
        "country": "United Kingdom",
        "followers": 45000000,
    },
    {
        "name": "Neymar Jr.",
        "profession": "a Footballer",
        "country": "Brazil",
        "followers": 210000000,
    },
    {
        "name": "Rihanna",
        "profession": "a Musician",
        "country": "Barbados",
        "followers": 150000000,
    },
    {
        "name": "Novak Djokovic",
        "profession": "a Tennis Player",
        "country": "Serbia",
        "followers": 14000000,
    },
    {
        "name": "Lady Gaga",
        "profession": "a Musician",
        "country": "United States",
        "followers": 56000000,
    },
    {
        "name": "Virat Kohli",
        "profession": "a Cricketer",
        "country": "India",
        "followers": 260000000,
    },
    {
        "name": "Drake",
        "profession": "a Musician",
        "country": "Canada",
        "followers": 140000000,
    },
    {
        "name": "Lewis Hamilton",
        "profession": "a Racing Driver",
        "country": "United Kingdom",
        "followers": 35000000,
    },
    {
        "name": "Ariana Grande",
        "profession": "a Musician",
        "country": "United States",
        "followers": 380000000,
    },
    {
        "name": "Kylian Mbappé",
        "profession": "a Footballer",
        "country": "France",
        "followers": 110000000,
    },
    {
        "name": "Billie Eilish",
        "profession": "a Musician",
        "country": "United States",
        "followers": 110000000,
    },
    {
        "name": "Megan Rapinoe",
        "profession": "a Footballer",
        "country": "United States",
        "followers": 2500000,
    },
    {
        "name": "Bad Bunny",
        "profession": "a Musician",
        "country": "Puerto Rico",
        "followers": 46000000,
    },
    {
        "name": "Mo Salah",
        "profession": "a Footballer",
        "country": "Egypt",
        "followers": 63000000,
    },
    {
        "name": "Bruno Mars",
        "profession": "a Musician",
        "country": "United States",
        "followers": 27000000,
    },
    {
        "name": "Robert Lewandowski",
        "profession": "a Footballer",
        "country": "Poland",
        "followers": 36000000,
    },
    {
        "name": "Dua Lipa",
        "profession": "a Musician",
        "country": "United Kingdom",
        "followers": 89000000,
    },
    {
        "name": "Kevin De Bruyne",
        "profession": "a Footballer",
        "country": "Belgium",
        "followers": 25000000,
    },
    {
        "name": "The Weeknd",
        "profession": "a Musician",
        "country": "Canada",
        "followers": 60000000,
    },
    {
        "name": "Sadio Mané",
        "profession": "a Footballer",
        "country": "Senegal",
        "followers": 15000000,
    },
    {
        "name": "Justin Bieber",
        "profession": "a Musician",
        "country": "Canada",
        "followers": 290000000,
    },
    {
        "name": "Son Heung-min",
        "profession": "a Footballer",
        "country": "South Korea",
        "followers": 17000000,
    },
    {
        "name": "Camila Cabello",
        "profession": "a Musician",
        "country": "Cuba",
        "followers": 67000000,
    },
    {
        "name": "Luka Modrić",
        "profession": "a Footballer",
        "country": "Croatia",
        "followers": 32000000,
    },
    {
        "name": "Shawn Mendes",
        "profession": "a Musician",
        "country": "Canada",
        "followers": 73000000,
    },
    {
        "name": "Antoine Griezmann",
        "profession": "a Footballer",
        "country": "France",
        "followers": 38000000,
    },
    {
        "name": "Maluma",
        "profession": "a Musician",
        "country": "Colombia",
        "followers": 63000000,
    },
    {
        "name": "Pierre-Emerick Aubameyang",
        "profession": "a Footballer",
        "country": "Gabon",
        "followers": 14000000,
    },
    {
        "name": "Enrique Iglesias",
        "profession": "a Musician",
        "country": "Spain",
        "followers": 18000000,
    },
    {
        "name": "Gareth Bale",
        "profession": "a Footballer",
        "country": "Wales",
        "followers": 5000000,
    },
    {
        "name": "Anitta",
        "profession": "a Musician",
        "country": "Brazil",
        "followers": 65000000,
    },
    {
        "name": "Zlatan Ibrahimović",
        "profession": "a Footballer",
        "country": "Sweden",
        "followers": 63000000,
    },
    {
        "name": "BLACKPINK",
        "profession": "a Music Group",
        "country": "South Korea",
        "followers": 57000000,
    },
    {
        "name": "Karim Benzema",
        "profession": "a Footballer",
        "country": "France",
        "followers": 74000000,
    },
    {
        "name": "J Balvin",
        "profession": "a Musician",
        "country": "Colombia",
        "followers": 54000000,
    },
    {
        "name": "Erling Haaland",
        "profession": "a Footballer",
        "country": "Norway",
        "followers": 40000000,
    },
    {
        "name": "Sia",
        "profession": "a Musician",
        "country": "Australia",
        "followers": 8000000,
    },
    {
        "name": "Marta",
        "profession": "a Footballer",
        "country": "Brazil",
        "followers": 3000000,
    },
    {
        "name": "Sam Smith",
        "profession": "a Musician",
        "country": "United Kingdom",
        "followers": 15000000,
    },
    {
        "name": "Sunil Chhetri",
        "profession": "a Footballer",
        "country": "India",
        "followers": 5000000,
    },
]
